---
version: '3'
services:
  postfix-dovecot:
    build: .
    image: "humpedli/docker-postfix-dovecot"
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
    volumes:
      - "./cert.pem:/etc/ssl/certs/fullchain.pem:ro"
      - "./key.pem:/etc/ssl/private/privkey.pem:ro"
      - ./mail:/home/vmail
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "HOSTNAME=example.com"
      - "CUSTOM_NETWORKS=172.0.0.0/8"
      - "POSTMASTER=postmaster@example.com"
      - "MYSQL_HOST=mysql"
      - "MYSQL_PORT=3306"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_DATABASE=mail"
    depends_on:
      - mysql
    restart: "always"
  mysql:
    image: mariadb:10
    environment:
      - "MYSQL_ROOT_PASSWORD=rootpwd"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_DATABASE=mail"
    volumes:
      - ./mysql:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8080:80
  admin:
    image: postfixadmin
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: mysql
      POSTFIXADMIN_DB_USER: user
      POSTFIXADMIN_DB_PASSWORD: password
      POSTFIXADMIN_DB_NAME: mail
    ports:
      - 8081:80
